CREATE TABLE IF NOT EXISTS api_tokens(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL UNIQUE,
    token VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY(user_id) REFERENCES users(id)
);