server:
  port: 5612
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hldspm
    username: myuser
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  security:
    logout:
      success-url: /login?logout
